__author__ = 'Chick Markley chick@eecs.berkeley.edu U.C. Berkeley'

# CONSTANT DEFINITIONS

VECTOR_TEMP = 0
VECTOR_UTRUE = 1
VECTOR_F_MINUS_AV = 2
VECTOR_F = 3
VECTOR_U = 4
VECTOR_ALPHA = 5
VECTOR_BETA_I = 6
VECTOR_BETA_J = 7
VECTOR_BETA_K = 8
VECTOR_DINV = 9
VECTOR_L1INV = 10
VECTOR_VALID = 11
VECTORS_RESERVED = 12